apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: istio-tls-external-secret
  namespace: istio-ingress

spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store

  target:
    name: gateway-tls
    template:
      type: kubernetes.io/tls

  data:
  - remoteRef:
      key: dev/istio-tls-certificate
      property: tls.crt
    secretKey: tls.crt
  - remoteRef:
      key: dev/istio-tls-certificate
      property: tls.key
    secretKey: tls.key