apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
  - "*"
  gateways:
    - istio-ingress/istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend.online-boutique.svc.cluster.local
        port:
          number: 80